name: transformer_utils
version: 0.2.6
description: Utilities relating to code generation, Dart analyzer, logging, etc. for use in Pub transformers.
authors:
  - Workiva UI Platform Team <uip@workiva.com>
  - Workiva Client Platform Team <cp@workiva.com>
  - Greg Littlefield <greg.littlefield@workiva.com>
  - Evan Weible <evan.weible@workiva.com>
homepage: https://github.com/Workiva/dart_transformer_utils

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  analyzer: ">=0.42.0"
  build: '<3.0.0'
  path: ^1.6.4
  source_span: ^1.5.5

dev_dependencies:
  dart_dev:
    git:
      url: git@github.com:hunterbreathat-wk/dart_dev.git
      ref: flutter-fix
  dart_style: ^1.3.3
  dependency_validator:
    git:
      url: git@github.com:hunterbreathat-wk/dependency_validator.git
      ref: flutter-fix
  test: ^1.9.3
